### ISSUE TITLE
Unable to access or update previously added metadata as a collaborator

### ISSUE THREAD

**Issue by elisavettorstensson** [EGA-archive/FEGA-Portals#11]
**FEGA node**
Sweden

**Affected portal**
Submitter Portal

**Describe the bug**
I was added as a collaborator on a submission that a researcher is currently working on. I attempted to review the metadata they added in the Submitter Portal, but I am unable to open or view any metadata added previously. My collaborator has granted me both "read" and "write" access to the submission. While I can add new items to the metadata, such as "add study", I am unable to open or edit the existing studies.

**To Reproduce**
1. Go to the Submitter Portal.
2. Click on the submission where you are listed as a collaborator, with "read&write" access.
3. Select a tab (e.g., studies, samples, experiments).
4. Click on a registered study to update the entry.
5. You will see an error preventing you from opening and updating the existing records.

**Expected behavior**
As a collaborator with "read and write" access, I should be able to open, view, and update any previously registered items (metadata), such as studies or samples, in the submission.

**Screenshots**

**This is an existing study that I do not have access to view and update**: 
![image](https://github.com/user-attachments/assets/041052f6-f300-4fa4-8093-58c48349ee1b)

**This is a study that I can add if I want in the same submission** : 
![image](https://github.com/user-attachments/assets/b1d5708c-79c4-4a7e-a20f-578c8fcce9c8)

**Environment (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser Google Chrome 
 - Version 129.0.6668.100 (Official Build) (32-bit)

**Additional context**

**Comment by sdelatorrep** [comment]
It seems this has been solved, as I can't reproduce it. Please, reopen if this is not the case. Thanks for reporting!
