### ISSUE TITLE
"array submission" doc link in Study section note is broken

### ISSUE THREAD

**Issue by kjellp** [EGA-archive/FEGA-Portals#4]
**FEGA node**
Norway

**Affected portal**
Submitter Portal in test (after new feature deployments 2024-09-17)

**Describe the bug**
In the Study section there is a new info note with a link to the array submission documentation on the main ega-arachive.org site.

**To Reproduce**
1. Click the link
2. And you get a page with this info: "Error 404: /submissions/1/__EGA_MAIN_URL__/submission/metadata/submission/array/ Not Found"

**Expected behavior**
Properly redirect the user to the intended docs, maybe in a new tab.

**Comment by sdelatorrep** [comment]
Fixed. Thanks, Kjell!
