### ISSUE TITLE
Sorting columns not working as expected

### ISSUE THREAD

**Issue by kjellp** [EGA-archive/FEGA-Portals#5]
**FEGA node**
Norway

**Affected portal**
Submitter Portal test (after new features deployment2024-09-17)

**Describe the bug**
Attempting to sort Samples in the table by ID does not sort the rows numerically, and by the Updated columns does not sort the rows correctly by date.

Same for Runs by ID (it's first correctly sorted by default in first view), but then clicking on sort does a an alphabetical sort instead of numerical it seems. It looks like the dates also gets sorted alphabetically in the Updated column.

**Expected behavior**
Numerical columns such as ID gets sorted numerically
Date based columns gets sorted by time

**Comment by sdelatorrep** [comment]
This has been fixed. Thanks for reporting!
