### ISSUE TITLE
Improve UI placement for "Reset Form" and "X" buttons to avoid confusion

### ISSUE THREAD

**Issue by elisavettorstensson** [EGA-archive/FEGA-Portals#7]
**FEGA node**
Sweden

**Affected portal**
Submitter Portal (test environment)

**Is your feature request related to a problem? Please describe.**
I'm often frustrated by the placement of the two different options, **Reset Form** and **X**, in the same area. As a user, I get the impression that pressing **X** will reset the entire form. Until recently, I always pressed **Update**  to return to the main page because I was worried that pressing **X** would reset the entire form.

**Describe the solution you'd like**
I suggest keeping the **X** button in the upper right corner as it is, but moving the **Reset Form** button to the lower right area, next to the other options like **Update** and **Delete.**

**Describe alternatives you've considered**
As a user, I can almost understand why there might be both a **Delete** option and a **Reset Form** option. However, I’m not entirely convinced that both are necessary.

**Additional context**
![image](https://github.com/user-attachments/assets/63e42f29-9bd5-4159-a163-152d51089853)

**Comment by sdelatorrep** [comment]
This has been fixed. Thanks for reporting!
