### ISSUE TITLE
Issue with the field "Design Name" under "Experiments" in Submitter Portal

### ISSUE THREAD

**Issue by mattiasstromberg** [EGA-archive/FEGA-Portals#8]
**FEGA node**
Sweden.

**Affected portal**
Submitter Portal (test environment).

**Describe the bug**
When updating an Experiment metadata record, the content of the mandatory field "Design Name" disappears and must be typed in again.

**To Reproduce**
1. Go to 'Experiments'
2. Click on the 'Edit' icon for an existing Experiment record.
3. Look at the content of the field 'Design Name' to see that it is empty and that the message 'Please fill out this field' appears.

**Expected behavior**
I expected that the content of the field 'Design Name' should remain when starting to update an Experiment.

**Screenshots**
Not applicable.

**Environment (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: chrome
 - Version: 

**Additional context**
Not applicable.

**Comment by sdelatorrep** [comment]
This has been fixed. Thanks for reporting!
